#!/usr/bin/env python
#
# Script to build the files found in this directory.
#
# Original author Rob Kutschke.
#

import os
Import('env')
Import('mu2e_helper')

helper=mu2e_helper(env);
rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [ ] )

helper.make_plugins( [ mainlib,
                       'mu2e_RecoDataProducts',
                       'mu2e_DataProducts',
                       'mu2e_KinKalGeom',
                       'KinKal_General',
                       'art_Framework_Core',
                       'art_Framework_Principal',
                       'art_Framework_Services_Registry',
                       'art_root_io_tfile_support',
                       'art_root_io_TFileService_service',
                       'art_Framework_Services_Optional_RandomNumberGenerator_service',
                       'art_Persistency_Common',
                       'art_Persistency_Provenance',
                       'art_Utilities',
                       'canvas',
                       'MF_MessageLogger',
                       'fhiclcpp',
                       'fhiclcpp_types',
                       'cetlib',
                       'cetlib_except',
                       'CLHEP',
                       rootlibs,
                     ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
